Improve wait logic (#728)
Improve wait logic to be more time precise in the following component
chart:

- embeding-usvc
- guardrails-usvc
- llm-uservice
- lvm-uservice
- retriever-usvc

Signed-off-by: Lianhao Lu <lianhao.lu@intel.com>

diff --git a/helm-charts/common/retriever-usvc/templates/deployment.yaml b/helm-charts/common/retriever-usvc/templates/deployment.yaml
--- a/helm-charts/common/retriever-usvc/templates/deployment.yaml
+++ b/helm-charts/common/retriever-usvc/templates/deployment.yaml
@@ -49,11 +49,13 @@ spec:
               TESTHOST=$(MILVUS_HOST);
               TESTPORT=$(MILVUS_PORT);
               {{- end }}
-              retry_count={{ .Values.retryCount | default 60 }};
-              j=1;
-              while ! nc -z ${TESTHOST} ${TESTPORT}; do
-                [[ $j -ge ${retry_count} ]] && echo "ERROR: ${TESTHOST}:${TESTPORT} is NOT reachable in $j seconds!" && exit 1;
-                j=$((j+1)); sleep 1;
+              wait_timeout={{ .Values.waitTimeout | default 1 }};
+              total_timeout={{ .Values.retryTimeoutSeconds | default 60 }};
+              j=0;
+              while ! nc -w ${wait_timeout} -z ${TESTHOST} ${TESTPORT}; do
+                j=$((j+wait_timeout));
+                [[ $j -ge ${total_timeout} ]] && echo "ERROR: ${TESTHOST}:${TESTPORT} is NOT reachable in $j seconds!" && exit 1;
+                j=$((j+2)); sleep 2;
               done;
               echo "${TESTHOST}:${TESTPORT} is reachable within $j seconds.";
       containers:
