Freeze Helm charts versions for release 1.3
Signed-off-by: CICD-at-OPEA <CICD@opea.dev>

diff --git a/microservices-connector/config/manifests/data-prep.yaml b/microservices-connector/config/manifests/data-prep.yaml
--- a/microservices-connector/config/manifests/data-prep.yaml
+++ b/microservices-connector/config/manifests/data-prep.yaml
@@ -8,26 +8,32 @@ kind: ConfigMap
 metadata:
   name: data-prep-config
   labels:
-    helm.sh/chart: data-prep-0-latest
+    helm.sh/chart: data-prep-1.3.0
     app.kubernetes.io/name: data-prep
     app.kubernetes.io/instance: data-prep
     app.kubernetes.io/version: "v1.0"
     app.kubernetes.io/managed-by: Helm
 data:
-  TEI_ENDPOINT: "http://data-prep-tei"
-  REDIS_URL: "redis://data-prep-redis-vector-db:6379"
-  INDEX_NAME: "rag-redis"
+  TEI_EMBEDDING_ENDPOINT: "http://data-prep-tei"
+  DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_REDIS"
+  REDIS_HOST: "data-prep-redis-vector-db"
+  REDIS_PORT: "6379"
+  REDIS_SSL: "false"
+  REDIS_PASSWORD: ""
+  REDIS_USERNAME: ""
+  INDEX_NAME: "rag_redis"
   KEY_INDEX_NAME: "file-keys"
   SEARCH_BATCH_SIZE: "10"
-  MILVUS_HOST: "data-prep-milvus"
-  MILVUS: ""
-  MILVUS_PORT: ""
+  EMBED_MODEL: ""
   HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
   HF_HOME: "/tmp/.cache/huggingface"
   http_proxy: ""
   https_proxy: ""
   no_proxy: ""
   LOGFLAG: ""
+  NUMBA_CACHE_DIR: "/tmp/numba/cache"
+  XDG_CACHE_HOME: "/tmp/fontconfig/cache"
+  MPLCONFIGDIR: "/tmp/matplotlib"
 ---
 # Source: data-prep/templates/service.yaml
 # Copyright (C) 2024 Intel Corporation
@@ -38,7 +44,7 @@ kind: Service
 metadata:
   name: data-prep
   labels:
-    helm.sh/chart: data-prep-0-latest
+    helm.sh/chart: data-prep-1.3.0
     app.kubernetes.io/name: data-prep
     app.kubernetes.io/instance: data-prep
     app.kubernetes.io/version: "v1.0"
@@ -47,7 +53,7 @@ spec:
   type: ClusterIP
   ports:
     - port: 6007
-      targetPort: 6007
+      targetPort: 5000
       protocol: TCP
       name: data-prep
   selector:
@@ -63,7 +69,7 @@ kind: Deployment
 metadata:
   name: data-prep
   labels:
-    helm.sh/chart: data-prep-0-latest
+    helm.sh/chart: data-prep-1.3.0
     app.kubernetes.io/name: data-prep
     app.kubernetes.io/instance: data-prep
     app.kubernetes.io/version: "v1.0"
@@ -76,12 +82,37 @@ spec:
       app.kubernetes.io/instance: data-prep
   template:
     metadata:
+      
       labels:
         app.kubernetes.io/name: data-prep
         app.kubernetes.io/instance: data-prep
-    spec:
+    spec:      
+      serviceAccountName: default
       securityContext:
         {}
+      initContainers:
+        - name: wait-for-db
+          envFrom:
+            - configMapRef:
+                name: data-prep-config
+            - configMapRef:
+                name: extra-env-config
+                optional: true
+          image: busybox:1.36
+          command: ["sh", "-c"]
+          args:
+            - |
+              TESTHOST=$(REDIS_HOST);
+              TESTPORT=$(REDIS_PORT);
+              wait_timeout=1;
+              total_timeout=60;
+              j=0;
+              while ! nc -w ${wait_timeout} -z ${TESTHOST} ${TESTPORT}; do
+                j=$((j+wait_timeout));
+                [[ $j -ge ${total_timeout} ]] && echo "ERROR: ${TESTHOST}:${TESTPORT} is NOT reachable in $j seconds!" && exit 1;
+                j=$((j+2)); sleep 2;
+              done;
+              echo "${TESTHOST}:${TESTPORT} is reachable within $j seconds.";
       containers:
         - name: data-prep
           envFrom:
@@ -95,26 +126,28 @@ spec:
             capabilities:
               drop:
               - ALL
-            readOnlyRootFilesystem: false
+            readOnlyRootFilesystem: true
             runAsNonRoot: true
             runAsUser: 1000
             seccompProfile:
               type: RuntimeDefault
-          image: "opea/dataprep-redis:latest"
+          image: "opea/dataprep:1.3"
           ports:
             - name: data-prep
-              containerPort: 6007
+              containerPort: 5000
               protocol: TCP
           volumeMounts:
             - mountPath: /tmp
               name: tmp
-          livenessProbe:
-            failureThreshold: 24
-            httpGet:
-              path: v1/health_check
-              port: data-prep
-            initialDelaySeconds: 5
-            periodSeconds: 5
+            - mountPath: /home/user/comps/dataprep/src/uploaded_files
+              name: uploaded-files
+            - mountPath: /home/user/nltk_data
+              name: nltk-data
+            - mountPath: /home/user/comps/dataprep/src/unstructuredio/yolo_x_layout
+              subPath: unstructuredio/yolo_x_layout
+              name: model-volume
+            - mountPath: /home/user/.config
+              name: user-config-data
           readinessProbe:
             httpGet:
               path: v1/health_check
@@ -129,7 +162,25 @@ spec:
             initialDelaySeconds: 5
             periodSeconds: 5
           resources:
-            {}
+            requests:
+              cpu: 100m
+              memory: 128Mi
       volumes:
         - name: tmp
           emptyDir: {}
+        - name: uploaded-files
+          emptyDir: {}
+        - name: user-config-data
+          emptyDir: {}
+        - name: model-volume
+          emptyDir: {}
+        - name: nltk-data
+          emptyDir: {}
+---
+# Source: data-prep/templates/serviceaccount.yaml
+# Copyright (C) 2024 Intel Corporation
+# SPDX-License-Identifier: Apache-2.0
+---
+# Source: data-prep/templates/servicemonitor.yaml
+# Copyright (C) 2024 Intel Corporation
+# SPDX-License-Identifier: Apache-2.0
diff --git a/microservices-connector/config/manifests/data-prep_milvus.yaml b/microservices-connector/config/manifests/data-prep_milvus.yaml
--- a/microservices-connector/config/manifests/data-prep_milvus.yaml
+++ b/microservices-connector/config/manifests/data-prep_milvus.yaml
@@ -241,10 +241,10 @@ kind: ConfigMap
 metadata:
   name: data-prep-tei-config
   labels:
-    helm.sh/chart: tei-0-latest
+    helm.sh/chart: tei-1.3.0
     app.kubernetes.io/name: tei
     app.kubernetes.io/instance: data-prep
-    app.kubernetes.io/version: "cpu-1.5"
+    app.kubernetes.io/version: "cpu-1.6"
     app.kubernetes.io/managed-by: Helm
 data:
   MODEL_ID: "BAAI/bge-base-en-v1.5"
@@ -258,6 +258,7 @@ data:
   HF_HUB_DISABLE_PROGRESS_BARS: "1"
   HF_HUB_ENABLE_HF_TRANSFER: "0"
   # More options for HPU
+  HF_TOKEN: "insert-your-huggingface-token-here"
 ---
 # Source: data-prep/templates/configmap.yaml
 # Copyright (C) 2024 Intel Corporation
@@ -268,67 +269,27 @@ kind: ConfigMap
 metadata:
   name: data-prep-config
   labels:
-    helm.sh/chart: data-prep-0-latest
+    helm.sh/chart: data-prep-1.3.0
     app.kubernetes.io/name: data-prep
     app.kubernetes.io/instance: data-prep
     app.kubernetes.io/version: "v1.0"
     app.kubernetes.io/managed-by: Helm
 data:
-  TEI_ENDPOINT: "http://data-prep-tei"
-  REDIS_URL: "redis://data-prep-redis-vector-db:6379"
-  INDEX_NAME: "rag-redis"
-  KEY_INDEX_NAME: "file-keys"
-  SEARCH_BATCH_SIZE: "10"
+  TEI_EMBEDDING_ENDPOINT: "http://data-prep-tei"
+  DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_MILVUS"
   MILVUS_HOST: "data-prep-milvus"
-  MILVUS: ""
   MILVUS_PORT: "19530"
   COLLECTION_NAME: "rag_milvus"
+  LOCAL_EMBEDDING_MODEL: ""
   HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
   HF_HOME: "/tmp/.cache/huggingface"
   http_proxy: ""
   https_proxy: ""
   no_proxy: ""
   LOGFLAG: ""
----
-# Source: data-prep/charts/milvus/charts/minio/templates/pvc.yaml
-apiVersion: v1
-kind: PersistentVolumeClaim
-metadata:
-  name: data-prep-minio
-  annotations:
-    helm.sh/resource-policy: keep
-  labels:
-    app: minio
-    chart: minio-8.0.17
-    release: data-prep
-    heritage: Helm
-spec:
-  accessModes:
-    - "ReadWriteOnce"
-  resources:
-    requests:
-      storage: "500Gi"
----
-# Source: data-prep/charts/milvus/templates/pvc.yaml
-apiVersion: v1
-kind: PersistentVolumeClaim
-metadata:
-  name: data-prep-milvus
-  namespace: default
-  annotations:
-    helm.sh/resource-policy: keep
-  labels:
-    helm.sh/chart: milvus-4.2.12
-    app.kubernetes.io/name: milvus
-    app.kubernetes.io/instance: data-prep
-    app.kubernetes.io/version: "2.4.12"
-    app.kubernetes.io/managed-by: Helm
-spec:
-  accessModes:
-  - "ReadWriteOnce"
-  resources:
-    requests:
-      storage: 50Gi
+  NUMBA_CACHE_DIR: "/tmp/numba/cache"
+  XDG_CACHE_HOME: "/tmp/fontconfig/cache"
+  MPLCONFIGDIR: "/tmp/matplotlib"
 ---
 # Source: data-prep/charts/milvus/charts/etcd/templates/svc-headless.yaml
 apiVersion: v1
@@ -444,10 +405,10 @@ kind: Service
 metadata:
   name: data-prep-tei
   labels:
-    helm.sh/chart: tei-0-latest
+    helm.sh/chart: tei-1.3.0
     app.kubernetes.io/name: tei
     app.kubernetes.io/instance: data-prep
-    app.kubernetes.io/version: "cpu-1.5"
+    app.kubernetes.io/version: "cpu-1.6"
     app.kubernetes.io/managed-by: Helm
 spec:
   type: ClusterIP
@@ -469,7 +430,7 @@ kind: Service
 metadata:
   name: data-prep
   labels:
-    helm.sh/chart: data-prep-0-latest
+    helm.sh/chart: data-prep-1.3.0
     app.kubernetes.io/name: data-prep
     app.kubernetes.io/instance: data-prep
     app.kubernetes.io/version: "v1.0"
@@ -478,7 +439,7 @@ spec:
   type: ClusterIP
   ports:
     - port: 6007
-      targetPort: 6010
+      targetPort: 5000
       protocol: TCP
       name: data-prep
   selector:
@@ -516,10 +477,6 @@ spec:
         checksum/config: e7c2f210eafb188a3d4d6c1149821983c33cbcc1433c9e04f2fc2648fa07dac7
     spec:
       serviceAccountName: "data-prep-minio"
-      securityContext:
-        runAsUser: 1000
-        runAsGroup: 1000
-        fsGroup: 1000
       containers:
         - name: minio
           image: "minio/minio:RELEASE.2023-03-20T20-16-18Z"
@@ -528,9 +485,7 @@ spec:
             - "/bin/sh"
             - "-ce"
             - "/usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export"
-          volumeMounts:
-            - name: export
-              mountPath: /export            
+          volumeMounts:            
           ports:
             - name: http
               containerPort: 9000
@@ -576,8 +531,7 @@ spec:
               memory: 2Gi      
       volumes:
         - name: export
-          persistentVolumeClaim:
-            claimName: data-prep-minio
+          emptyDir: {}
         - name: minio-user
           secret:
             secretName: data-prep-minio
@@ -678,8 +632,7 @@ spec:
         configMap:
           name: data-prep-milvus
       - name: milvus-data-disk
-        persistentVolumeClaim:
-          claimName: data-prep-milvus
+        emptyDir: {}
       - name: disk
         emptyDir: {}
 ---
@@ -692,10 +645,10 @@ kind: Deployment
 metadata:
   name: data-prep-tei
   labels:
-    helm.sh/chart: tei-0-latest
+    helm.sh/chart: tei-1.3.0
     app.kubernetes.io/name: tei
     app.kubernetes.io/instance: data-prep
-    app.kubernetes.io/version: "cpu-1.5"
+    app.kubernetes.io/version: "cpu-1.6"
     app.kubernetes.io/managed-by: Helm
 spec:
   selector:
@@ -704,12 +657,50 @@ spec:
       app.kubernetes.io/instance: data-prep
   template:
     metadata:
+      
       labels:
         app.kubernetes.io/name: tei
         app.kubernetes.io/instance: data-prep
-    spec:
+    spec:      
+      serviceAccountName: default
       securityContext:
         {}
+      initContainers:
+        - name: model-downloader
+          envFrom:
+            - configMapRef:
+                name: data-prep-tei-config
+          securityContext:
+            readOnlyRootFilesystem: true
+            allowPrivilegeEscalation: false
+            runAsGroup: 0
+            capabilities:
+              drop:
+              - ALL
+              add:
+              - DAC_OVERRIDE
+              # To be able to make data model directory group writable for
+              # previously downloaded model by old versions of helm chart
+              - FOWNER
+            seccompProfile:
+              type: RuntimeDefault
+          image: huggingface/downloader:0.17.3
+          command: ['sh', '-ec']
+          args:
+            - |
+              echo "Huggingface log in ...";
+              huggingface-cli login --token $(HF_TOKEN);
+              echo "Download model BAAI/bge-base-en-v1.5 ... ";
+              huggingface-cli download --cache-dir /data "BAAI/bge-base-en-v1.5";
+              echo "Change model files mode ...";
+              chmod -R g+w /data/models--BAAI--bge-base-en-v1.5;
+              # NOTE: Buggy logout command;
+              # huggingface-cli logout;
+          volumeMounts:
+            - mountPath: /data
+              name: model-volume
+            - mountPath: /tmp
+              name: tmp
       containers:
         - name: tei
           envFrom:
@@ -719,7 +710,16 @@ spec:
                 name: extra-env-config
                 optional: true
           securityContext:
-            {}
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+              - ALL
+            readOnlyRootFilesystem: true
+            runAsGroup: 0
+            runAsNonRoot: true
+            runAsUser: 1000
+            seccompProfile:
+              type: RuntimeDefault
           image: "ghcr.io/huggingface/text-embeddings-inference:cpu-1.5"
           args:
             - "--auto-truncate"
@@ -734,14 +734,6 @@ spec:
             - name: http
               containerPort: 2081
               protocol: TCP
-          livenessProbe:
-            failureThreshold: 24
-            httpGet:
-              path: /health
-              port: http
-            initialDelaySeconds: 5
-            periodSeconds: 5
-            timeoutSeconds: 2
           readinessProbe:
             httpGet:
               path: /health
@@ -757,7 +749,9 @@ spec:
             initialDelaySeconds: 5
             periodSeconds: 5
           resources:
-            {}
+            requests:
+              cpu: 100m
+              memory: 128Mi
       volumes:
         - name: model-volume
           hostPath:
@@ -781,7 +775,7 @@ kind: Deployment
 metadata:
   name: data-prep
   labels:
-    helm.sh/chart: data-prep-0-latest
+    helm.sh/chart: data-prep-1.3.0
     app.kubernetes.io/name: data-prep
     app.kubernetes.io/instance: data-prep
     app.kubernetes.io/version: "v1.0"
@@ -794,12 +788,37 @@ spec:
       app.kubernetes.io/instance: data-prep
   template:
     metadata:
+      
       labels:
         app.kubernetes.io/name: data-prep
         app.kubernetes.io/instance: data-prep
-    spec:
+    spec:      
+      serviceAccountName: default
       securityContext:
         {}
+      initContainers:
+        - name: wait-for-db
+          envFrom:
+            - configMapRef:
+                name: data-prep-config
+            - configMapRef:
+                name: extra-env-config
+                optional: true
+          image: busybox:1.36
+          command: ["sh", "-c"]
+          args:
+            - |
+              TESTHOST=$(MILVUS_HOST);
+              TESTPORT=$(MILVUS_PORT);
+              wait_timeout=1;
+              total_timeout=60;
+              j=0;
+              while ! nc -w ${wait_timeout} -z ${TESTHOST} ${TESTPORT}; do
+                j=$((j+wait_timeout));
+                [[ $j -ge ${total_timeout} ]] && echo "ERROR: ${TESTHOST}:${TESTPORT} is NOT reachable in $j seconds!" && exit 1;
+                j=$((j+2)); sleep 2;
+              done;
+              echo "${TESTHOST}:${TESTPORT} is reachable within $j seconds.";
       containers:
         - name: data-prep
           envFrom:
@@ -813,26 +832,28 @@ spec:
             capabilities:
               drop:
               - ALL
-            readOnlyRootFilesystem: false
+            readOnlyRootFilesystem: true
             runAsNonRoot: true
             runAsUser: 1000
             seccompProfile:
               type: RuntimeDefault
-          image: "opea/dataprep-milvus:latest"
+          image: "opea/dataprep:1.3"
           ports:
             - name: data-prep
-              containerPort: 6010
+              containerPort: 5000
               protocol: TCP
           volumeMounts:
             - mountPath: /tmp
               name: tmp
-          livenessProbe:
-            failureThreshold: 24
-            httpGet:
-              path: v1/health_check
-              port: data-prep
-            initialDelaySeconds: 5
-            periodSeconds: 5
+            - mountPath: /home/user/comps/dataprep/src/uploaded_files
+              name: uploaded-files
+            - mountPath: /home/user/nltk_data
+              name: nltk-data
+            - mountPath: /home/user/comps/dataprep/src/unstructuredio/yolo_x_layout
+              subPath: unstructuredio/yolo_x_layout
+              name: model-volume
+            - mountPath: /home/user/.config
+              name: user-config-data
           readinessProbe:
             httpGet:
               path: v1/health_check
@@ -847,9 +868,19 @@ spec:
             initialDelaySeconds: 5
             periodSeconds: 5
           resources:
-            {}
+            requests:
+              cpu: 100m
+              memory: 128Mi
       volumes:
         - name: tmp
+          emptyDir: {}
+        - name: uploaded-files
+          emptyDir: {}
+        - name: user-config-data
+          emptyDir: {}
+        - name: model-volume
+          emptyDir: {}
+        - name: nltk-data
           emptyDir: {}
 ---
 # Source: data-prep/charts/milvus/charts/etcd/templates/statefulset.yaml
@@ -987,20 +1018,25 @@ spec:
             - name: data
               mountPath: /bitnami/etcd
       volumes:
-  volumeClaimTemplates:
-    - metadata:
-        name: data
-      spec:
-        accessModes:
-          - "ReadWriteOnce"
-        resources:
-          requests:
-            storage: "10Gi"
+        - name: data
+          emptyDir: {}
 ---
 # Source: data-prep/charts/tei/templates/horizontal-pod-autoscaler.yaml
 # Copyright (C) 2024 Intel Corporation
 # SPDX-License-Identifier: Apache-2.0
 ---
+# Source: data-prep/charts/tei/templates/serviceaccount.yaml
+# Copyright (C) 2024 Intel Corporation
+# SPDX-License-Identifier: Apache-2.0
+---
 # Source: data-prep/charts/tei/templates/servicemonitor.yaml
+# Copyright (C) 2024 Intel Corporation
+# SPDX-License-Identifier: Apache-2.0
+---
+# Source: data-prep/templates/serviceaccount.yaml
+# Copyright (C) 2024 Intel Corporation
+# SPDX-License-Identifier: Apache-2.0
+---
+# Source: data-prep/templates/servicemonitor.yaml
 # Copyright (C) 2024 Intel Corporation
 # SPDX-License-Identifier: Apache-2.0
diff --git a/microservices-connector/config/manifests/retriever-usvc.yaml b/microservices-connector/config/manifests/retriever-usvc.yaml
--- a/microservices-connector/config/manifests/retriever-usvc.yaml
+++ b/microservices-connector/config/manifests/retriever-usvc.yaml
@@ -8,18 +8,21 @@ kind: ConfigMap
 metadata:
   name: retriever-usvc-config
   labels:
-    helm.sh/chart: retriever-usvc-0-latest
+    helm.sh/chart: retriever-usvc-1.3.0
     app.kubernetes.io/name: retriever-usvc
     app.kubernetes.io/instance: retriever-usvc
     app.kubernetes.io/version: "v1.0"
     app.kubernetes.io/managed-by: Helm
 data:
   TEI_EMBEDDING_ENDPOINT: "http://retriever-usvc-tei"
-  REDIS_URL: "redis://retriever-usvc-redis-vector-db:6379"
-  INDEX_NAME: "rag-redis"
-  MILVUS_HOST: "retriever-usvc-milvus"
-  MILVUS: ""
-  MILVUS_PORT: ""
+  RETRIEVER_COMPONENT_NAME: "OPEA_RETRIEVER_REDIS"
+  REDIS_HOST: "retriever-usvc-redis-vector-db"
+  REDIS_PORT: "6379"
+  REDIS_SSL: "false"
+  REDIS_PASSWORD: ""
+  REDIS_USERNAME: ""
+  INDEX_NAME: "rag_redis"
+  EMBED_MODEL: ""
   EASYOCR_MODULE_PATH: "/tmp/.EasyOCR"
   http_proxy: ""
   https_proxy: ""
@@ -27,6 +30,9 @@ data:
   HF_HOME: "/tmp/.cache/huggingface"
   HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
   LOGFLAG: ""
+  NUMBA_CACHE_DIR: "/tmp/numba/cache"
+  MPLCONFIGDIR: "/tmp/matplotlib"
+  HAYSTACK_TELEMETRY_ENABLED: "False"
 ---
 # Source: retriever-usvc/templates/service.yaml
 # Copyright (C) 2024 Intel Corporation
@@ -37,7 +43,7 @@ kind: Service
 metadata:
   name: retriever-usvc
   labels:
-    helm.sh/chart: retriever-usvc-0-latest
+    helm.sh/chart: retriever-usvc-1.3.0
     app.kubernetes.io/name: retriever-usvc
     app.kubernetes.io/instance: retriever-usvc
     app.kubernetes.io/version: "v1.0"
@@ -62,7 +68,7 @@ kind: Deployment
 metadata:
   name: retriever-usvc
   labels:
-    helm.sh/chart: retriever-usvc-0-latest
+    helm.sh/chart: retriever-usvc-1.3.0
     app.kubernetes.io/name: retriever-usvc
     app.kubernetes.io/instance: retriever-usvc
     app.kubernetes.io/version: "v1.0"
@@ -75,12 +81,37 @@ spec:
       app.kubernetes.io/instance: retriever-usvc
   template:
     metadata:
+      
       labels:
         app.kubernetes.io/name: retriever-usvc
         app.kubernetes.io/instance: retriever-usvc
-    spec:
+    spec:      
+      serviceAccountName: default
       securityContext:
         {}
+      initContainers:
+        - name: wait-for-db
+          envFrom:
+            - configMapRef:
+                name: retriever-usvc-config
+            - configMapRef:
+                name: extra-env-config
+                optional: true
+          image: busybox:1.36
+          command: ["sh", "-c"]
+          args:
+            - |
+              TESTHOST=$(REDIS_HOST);
+              TESTPORT=$(REDIS_PORT);
+              wait_timeout=1;
+              total_timeout=60;
+              j=0;
+              while ! nc -w ${wait_timeout} -z ${TESTHOST} ${TESTPORT}; do
+                j=$((j+wait_timeout));
+                [[ $j -ge ${total_timeout} ]] && echo "ERROR: ${TESTHOST}:${TESTPORT} is NOT reachable in $j seconds!" && exit 1;
+                j=$((j+2)); sleep 2;
+              done;
+              echo "${TESTHOST}:${TESTPORT} is reachable within $j seconds.";
       containers:
         - name: retriever-usvc
           envFrom:
@@ -99,7 +130,7 @@ spec:
             runAsUser: 1000
             seccompProfile:
               type: RuntimeDefault
-          image: "opea/retriever-redis:latest"
+          image: "opea/retriever:1.3"
           ports:
             - name: retriever-usvc
               containerPort: 7000
@@ -107,13 +138,8 @@ spec:
           volumeMounts:
             - mountPath: /tmp
               name: tmp
-          livenessProbe:
-            failureThreshold: 24
-            httpGet:
-              path: v1/health_check
-              port: retriever-usvc
-            initialDelaySeconds: 5
-            periodSeconds: 5
+            - mountPath: /home/user/nltk_data
+              name: nltk-data
           readinessProbe:
             httpGet:
               path: v1/health_check
@@ -128,10 +154,18 @@ spec:
             initialDelaySeconds: 5
             periodSeconds: 5
           resources:
-            {}
+            requests:
+              cpu: 100m
+              memory: 128Mi
       volumes:
         - name: tmp
           emptyDir: {}
+        - name: nltk-data
+          emptyDir: {}
+---
+# Source: retriever-usvc/templates/serviceaccount.yaml
+# Copyright (C) 2024 Intel Corporation
+# SPDX-License-Identifier: Apache-2.0
 ---
 # Source: retriever-usvc/templates/servicemonitor.yaml
 # Copyright (C) 2024 Intel Corporation
