Freeze Helm charts versions for release 1.2
Signed-off-by: CICD-at-OPEA <CICD@opea.dev>

diff --git a/microservices-connector/config/manifests/faqgen-llm-uservice.yaml b/microservices-connector/config/manifests/faqgen-llm-uservice.yaml
--- a/microservices-connector/config/manifests/faqgen-llm-uservice.yaml
+++ b/microservices-connector/config/manifests/faqgen-llm-uservice.yaml
@@ -8,16 +8,17 @@ kind: ConfigMap
 metadata:
   name: faqgen-llm-uservice-config
   labels:
-    helm.sh/chart: llm-uservice-0-latest
+    helm.sh/chart: llm-uservice-1.2.0
     app.kubernetes.io/name: llm-uservice
     app.kubernetes.io/instance: faqgen-llm-uservice
     app.kubernetes.io/version: "v1.0"
     app.kubernetes.io/managed-by: Helm
 data:
-  TGI_LLM_ENDPOINT: "http://faqgen-llm-uservice-tgi"
-  vLLM_ENDPOINT: "http://faqgen-llm-uservice-vllm"
-  HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
+  FAQGen_COMPONENT_NAME: "OpeaFaqGenTgi"
+  LLM_ENDPOINT: "http://faqgen-llm-uservice-tgi"
+  LLM_MODEL_ID: "meta-llama/Meta-Llama-3-8B-Instruct"
   HF_HOME: "/tmp/.cache/huggingface"
+  HF_TOKEN: "insert-your-huggingface-token-here"
   http_proxy: ""
   https_proxy: ""
   no_proxy: ""
@@ -32,7 +33,7 @@ kind: Service
 metadata:
   name: faqgen-llm-uservice
   labels:
-    helm.sh/chart: llm-uservice-0-latest
+    helm.sh/chart: llm-uservice-1.2.0
     app.kubernetes.io/name: llm-uservice
     app.kubernetes.io/instance: faqgen-llm-uservice
     app.kubernetes.io/version: "v1.0"
@@ -57,7 +58,7 @@ kind: Deployment
 metadata:
   name: faqgen-llm-uservice
   labels:
-    helm.sh/chart: llm-uservice-0-latest
+    helm.sh/chart: llm-uservice-1.2.0
     app.kubernetes.io/name: llm-uservice
     app.kubernetes.io/instance: faqgen-llm-uservice
     app.kubernetes.io/version: "v1.0"
@@ -74,10 +75,11 @@ spec:
         app.kubernetes.io/name: llm-uservice
         app.kubernetes.io/instance: faqgen-llm-uservice
     spec:
+      serviceAccountName: default
       securityContext:
         {}
-      containers:
-        - name: faqgen-llm-uservice
+      initContainers:
+        - name: wait-for-llm
           envFrom:
             - configMapRef:
                 name: faqgen-llm-uservice-config
@@ -94,7 +96,45 @@ spec:
             runAsUser: 1000
             seccompProfile:
               type: RuntimeDefault
-          image: "opea/llm-faqgen-tgi:latest"
+          image: busybox:1.36
+          command: ["sh", "-c"]
+          args:
+            - |
+              proto=$(echo ${LLM_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\1/p');
+              host=$(echo ${LLM_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\2/p');
+              port=$(echo ${LLM_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\3/p');
+              if [ -z "$port" ]; then
+                  port=80;
+                  [[ "$proto" = "https" ]] && port=443;
+              fi;
+              wait_timeout=1;
+              total_timeout=60;
+              j=0;
+              while ! nc -w ${wait_timeout} -z ${host} ${port}; do
+                j=$((j+wait_timeout));
+                [[ $j -ge ${total_timeout} ]] && echo "ERROR: ${host}:${port} is NOT reachable in $j seconds!" && exit 1;
+                j=$((j+2)); sleep 2;
+              done;
+              echo "${host}:${port} is reachable within $j seconds.";
+      containers:
+        - name: llm-uservice
+          envFrom:
+            - configMapRef:
+                name: faqgen-llm-uservice-config
+            - configMapRef:
+                name: extra-env-config
+                optional: true
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+              - ALL
+            readOnlyRootFilesystem: false
+            runAsNonRoot: true
+            runAsUser: 1000
+            seccompProfile:
+              type: RuntimeDefault
+          image: "opea/llm-faqgen:1.2"
           ports:
             - name: llm-uservice
               containerPort: 9000
@@ -102,13 +142,6 @@ spec:
           volumeMounts:
             - mountPath: /tmp
               name: tmp
-          livenessProbe:
-            failureThreshold: 24
-            httpGet:
-              path: v1/health_check
-              port: llm-uservice
-            initialDelaySeconds: 5
-            periodSeconds: 5
           readinessProbe:
             httpGet:
               path: v1/health_check
@@ -123,10 +156,16 @@ spec:
             initialDelaySeconds: 5
             periodSeconds: 5
           resources:
-            {}
+            requests:
+              cpu: 100m
+              memory: 128Mi
       volumes:
         - name: tmp
           emptyDir: {}
+---
+# Source: llm-uservice/templates/serviceaccount.yaml
+# Copyright (C) 2024 Intel Corporation
+# SPDX-License-Identifier: Apache-2.0
 ---
 # Source: llm-uservice/templates/servicemonitor.yaml
 # Copyright (C) 2024 Intel Corporation
diff --git a/microservices-connector/config/manifests/guardrails-usvc.yaml b/microservices-connector/config/manifests/guardrails-usvc.yaml
--- a/microservices-connector/config/manifests/guardrails-usvc.yaml
+++ b/microservices-connector/config/manifests/guardrails-usvc.yaml
@@ -8,14 +8,15 @@ kind: ConfigMap
 metadata:
   name: guardrails-usvc-config
   labels:
-    helm.sh/chart: guardrails-usvc-0-latest
+    helm.sh/chart: guardrails-usvc-1.2.0
     app.kubernetes.io/name: guardrails-usvc
     app.kubernetes.io/instance: guardrails-usvc
     app.kubernetes.io/version: "v1.0"
     app.kubernetes.io/managed-by: Helm
 data:
-  SAFETY_GUARD_ENDPOINT: "http://guardrails-usvc-tgi"
+  SAFETY_GUARD_ENDPOINT: "http://guardrails-usvc-tgi-guardrails"
   SAFETY_GUARD_MODEL_ID: "meta-llama/Meta-Llama-Guard-2-8B"
+  GUARDRAILS_COMPONENT_NAME: "OPEA_LLAMA_GUARD"
   HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
   HF_HOME: "/tmp/.cache/huggingface"
   LOGFLAG: ""
@@ -32,7 +33,7 @@ kind: Service
 metadata:
   name: guardrails-usvc
   labels:
-    helm.sh/chart: guardrails-usvc-0-latest
+    helm.sh/chart: guardrails-usvc-1.2.0
     app.kubernetes.io/name: guardrails-usvc
     app.kubernetes.io/instance: guardrails-usvc
     app.kubernetes.io/version: "v1.0"
@@ -57,7 +58,7 @@ kind: Deployment
 metadata:
   name: guardrails-usvc
   labels:
-    helm.sh/chart: guardrails-usvc-0-latest
+    helm.sh/chart: guardrails-usvc-1.2.0
     app.kubernetes.io/name: guardrails-usvc
     app.kubernetes.io/instance: guardrails-usvc
     app.kubernetes.io/version: "v1.0"
@@ -74,8 +75,47 @@ spec:
         app.kubernetes.io/name: guardrails-usvc
         app.kubernetes.io/instance: guardrails-usvc
     spec:
+      serviceAccountName: default
       securityContext:
         {}
+      initContainers:
+        - name: wait-for-llm
+          envFrom:
+            - configMapRef:
+                name: guardrails-usvc-config
+            - configMapRef:
+                name: extra-env-config
+                optional: true
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+              - ALL
+            readOnlyRootFilesystem: true
+            runAsNonRoot: true
+            runAsUser: 1000
+            seccompProfile:
+              type: RuntimeDefault
+          image: busybox:1.36
+          command: ["sh", "-c"]
+          args:
+            - |
+              proto=$(echo ${SAFETY_GUARD_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\1/p');
+              host=$(echo ${SAFETY_GUARD_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\2/p');
+              port=$(echo ${SAFETY_GUARD_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\3/p');
+              if [ -z "$port" ]; then
+                  port=80;
+                  [[ "$proto" = "https" ]] && port=443;
+              fi;
+              wait_timeout=1;
+              total_timeout=60;
+              j=0;
+              while ! nc -w ${wait_timeout} -z ${host} ${port}; do
+                j=$((j+wait_timeout));
+                [[ $j -ge ${total_timeout} ]] && echo "ERROR: ${host}:${port} is NOT reachable in $j seconds!" && exit 1;
+                j=$((j+2)); sleep 2;
+              done;
+              echo "${host}:${port} is reachable within $j seconds.";
       containers:
         - name: guardrails-usvc
           envFrom:
@@ -94,7 +134,7 @@ spec:
             runAsUser: 1000
             seccompProfile:
               type: RuntimeDefault
-          image: "opea/guardrails-tgi:latest"
+          image: "opea/guardrails:1.2"
           ports:
             - name: guardrails-usvc
               containerPort: 9090
@@ -102,13 +142,6 @@ spec:
           volumeMounts:
             - mountPath: /tmp
               name: tmp
-          livenessProbe:
-            failureThreshold: 24
-            httpGet:
-              path: v1/health_check
-              port: guardrails-usvc
-            initialDelaySeconds: 5
-            periodSeconds: 5
           readinessProbe:
             httpGet:
               path: v1/health_check
@@ -123,7 +156,13 @@ spec:
             initialDelaySeconds: 5
             periodSeconds: 5
           resources:
-            {}
+            requests:
+              cpu: 100m
+              memory: 128Mi
       volumes:
         - name: tmp
           emptyDir: {}
+---
+# Source: guardrails-usvc/templates/serviceaccount.yaml
+# Copyright (C) 2024 Intel Corporation
+# SPDX-License-Identifier: Apache-2.0
diff --git a/microservices-connector/config/manifests/lvm-uservice.yaml b/microservices-connector/config/manifests/lvm-uservice.yaml
--- a/microservices-connector/config/manifests/lvm-uservice.yaml
+++ b/microservices-connector/config/manifests/lvm-uservice.yaml
@@ -8,14 +8,15 @@ kind: ConfigMap
 metadata:
   name: lvm-uservice-config
   labels:
-    helm.sh/chart: lvm-uservice-0-latest
+    helm.sh/chart: lvm-uservice-1.2.0
     app.kubernetes.io/name: lvm-uservice
     app.kubernetes.io/instance: lvm-uservice
     app.kubernetes.io/version: "v1.0"
     app.kubernetes.io/managed-by: Helm
 data:
+  LVM_COMPONENT_NAME: "OPEA_TGI_LLAVA_LVM"
   LVM_ENDPOINT: "http://lvm-uservice-tgi"
-  HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
+  HF_TOKEN: "insert-your-huggingface-token-here"
   HF_HOME: "/tmp/.cache/huggingface"
   http_proxy: ""
   https_proxy: ""
@@ -31,7 +32,7 @@ kind: Service
 metadata:
   name: lvm-uservice
   labels:
-    helm.sh/chart: lvm-uservice-0-latest
+    helm.sh/chart: lvm-uservice-1.2.0
     app.kubernetes.io/name: lvm-uservice
     app.kubernetes.io/instance: lvm-uservice
     app.kubernetes.io/version: "v1.0"
@@ -56,7 +57,7 @@ kind: Deployment
 metadata:
   name: lvm-uservice
   labels:
-    helm.sh/chart: lvm-uservice-0-latest
+    helm.sh/chart: lvm-uservice-1.2.0
     app.kubernetes.io/name: lvm-uservice
     app.kubernetes.io/instance: lvm-uservice
     app.kubernetes.io/version: "v1.0"
@@ -73,8 +74,47 @@ spec:
         app.kubernetes.io/name: lvm-uservice
         app.kubernetes.io/instance: lvm-uservice
     spec:
+      serviceAccountName: default
       securityContext:
         {}
+      initContainers:
+        - name: wait-for-lvm
+          envFrom:
+            - configMapRef:
+                name: lvm-uservice-config
+            - configMapRef:
+                name: extra-env-config
+                optional: true
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+              - ALL
+            readOnlyRootFilesystem: false
+            runAsNonRoot: true
+            runAsUser: 1000
+            seccompProfile:
+              type: RuntimeDefault
+          image: busybox:1.36
+          command: ["sh", "-c"]
+          args:
+            - |
+              proto=$(echo ${LVM_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\1/p');
+              host=$(echo ${LVM_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\2/p');
+              port=$(echo ${LVM_ENDPOINT} | sed -n 's/.*\(http[s]\?\):\/\/\([^ :]\+\):\?\([0-9]*\).*/\3/p');
+              if [ -z "$port" ]; then
+                  port=80;
+                  [[ "$proto" = "https" ]] && port=443;
+              fi;
+              wait_timeout=1;
+              total_timeout=60;
+              j=0;
+              while ! nc -w ${wait_timeout} -z ${host} ${port}; do
+                j=$((j+wait_timeout));
+                [[ $j -ge ${total_timeout} ]] && echo "ERROR: ${host}:${port} is NOT reachable in $j seconds!" && exit 1;
+                j=$((j+2)); sleep 2;
+              done;
+              echo "${host}:${port} is reachable within $j seconds.";
       containers:
         - name: lvm-uservice
           envFrom:
@@ -93,7 +133,7 @@ spec:
             runAsUser: 1000
             seccompProfile:
               type: RuntimeDefault
-          image: "opea/lvm-tgi:latest"
+          image: "opea/lvm:1.2"
           ports:
             - name: lvm-uservice
               containerPort: 9399
@@ -101,19 +141,13 @@ spec:
           volumeMounts:
             - mountPath: /tmp
               name: tmp
-          livenessProbe:
-            failureThreshold: 24
-            httpGet:
-              path: v1/health_check
-              port: lvm-uservice
-            initialDelaySeconds: 5
-            periodSeconds: 5
           readinessProbe:
             httpGet:
               path: v1/health_check
               port: lvm-uservice
             initialDelaySeconds: 5
             periodSeconds: 5
+            timeoutSeconds: 5
           startupProbe:
             failureThreshold: 120
             httpGet:
@@ -122,10 +156,16 @@ spec:
             initialDelaySeconds: 5
             periodSeconds: 5
           resources:
-            {}
+            requests:
+              cpu: 100m
+              memory: 128Mi
       volumes:
         - name: tmp
           emptyDir: {}
+---
+# Source: lvm-uservice/templates/serviceaccount.yaml
+# Copyright (C) 2024 Intel Corporation
+# SPDX-License-Identifier: Apache-2.0
 ---
 # Source: lvm-uservice/templates/servicemonitor.yaml
 # Copyright (C) 2024 Intel Corporation
